FROM ros:jazzy-perception

WORKDIR /tmp

# depthai-core
RUN git clone -b main https://github.com/luxonis/depthai-core.git && cd depthai-core && git submodule update --init --recursive && \
  mkdir build && cd build && cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local && \
  make -j4 && make install && \
  rm -rf /tmp/* /root/*

USER ubuntu
WORKDIR /home/ubuntu

# nvim & tmux
RUN mkdir .config && cd .config && \ 
  git clone -b 24.04+ https://github.com/minrui-hust/nvim.git && \
  git clone -b master https://github.com/minrui-hust/tmux.git

USER root

RUN cd .config/nvim && ./install.bash && rm -rf /tmp/* && \
  apt-get install -y \
  tmux \
  exuberant-ctags \
  ssh-client \
  ros-jazzy-rviz2 \
  clangd && \
  apt-get autoclean && rm -rf /var/lib/apt/lists/*

RUN echo "ubuntu:123" | chpasswd



RUN echo \
"\n \
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@cityfly\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '\n \
\n \
source /opt/ros/jazzy/setup.bash\n \
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp\n \
export FASTRTPS_DEFAULT_PROFILES_FILE=/home/ubuntu/cityfly/src/common/fastrtps.xml\n \
" >> /home/ubuntu/.bashrc

USER ubuntu
WORKDIR /home/ubuntu/cityfly
ENTRYPOINT [ "/bin/bash" ]

